config/routes.rb
Rails.application.routes.draw do
  root 'home#index' 
  devise_for :usuarios
  devise_for :administradores
  resources :productos
  resources :categorias
  resources :carros, only: [:show, :update] do
    member do 
      post  :pagar_con_paypal
      get   :procesar_pago_paypal
    end
  end

end

app/controllers/carros_controller.rb
class CarrosController < ApplicationController
  before_action :authenticate_usuario!
  def update
      producto = params[:carro][:producto_id]
      cantidad = params[:carro][:cantidad]

      orden_actual.agregar_producto(producto, cantidad)

      redirect_to root_url, notice: 'Producto agregado 🤑'
  end
  def show
      @orden = orden_actual
  end
    # POST
    def pagar_con_paypal
      orden = Orden.find(params[:carro][:orden_id])
      #price must be in cents
      price = 100
      # Aqui llamamos al express gateway que definimos al inicializar
      # que definimos en nuestro archivo config/development.rb y
      # preparamos la compra, donde se nos devolverá un token para
      # identificar esta venta en particular
      response = EXPRESS_GATEWAY.setup_purchase(price,
          ip: request.remote_ip,
          return_url: procesar_pago_paypal_carro_url,
          cancel_return_url: root_url,
          allow_guest_checkout: true,
          currency: "USD"
      )
      payment_method = MetodoPago.find_by(codigo: "PEC")
      # Aquí creamos nuestro registro en la tabla Payment con el
      # payment method de Paypal, y con estado “processing” pues aún
      # está en proceso
      Pago.create(
          orden_id: orden.id,
          metodo_pago_id: payment_method.id,
          estado: "processing",
          total: orden.total,
          token: response.token
      )
      # redirigimos al usuario a Paypal, para que realice el pago
      redirect_to EXPRESS_GATEWAY.redirect_url_for(response.token), allow_other_host: true
  end
  
  # GET
  def procesar_pago_paypal
      details = EXPRESS_GATEWAY.details_for(params[:token])
      express_purchase_options =
      {
          ip: request.remote_ip,
          token: params[:token],
          payer_id: details.payer_id,
          currency: "USD"
      }
      price = details.params["order_total"].to_d * 100
      response = EXPRESS_GATEWAY.purchase(price, express_purchase_options)
      if response.success?
          payment = Pago.find_by(token: response.token)
          order = payment.orden
          #update object states
          payment.estado = "completed"
          order.estado = "completed"
          ActiveRecord::Base.transaction do
              order.save!
              payment.save!
          end
      end
  end
  
  
end

app/views/carros/procesar_pago_paypal.html.erb
🤑🎉🎇 FELICIDADES POR LA COMPRA

<%= link_to "Volver a comprar" , root_path %>

app/views/carros/show.html.erb
<div class="card">
    <div class="card-header bg-dark text-light">
        <i class="fa fa-shopping-cart" aria-hidden="true"></i>
        <a href="<%= root_url%>" class="btn btn-outline-info btn-sm pull-right">Continuar comprando</a>
        <div class="clearfix"></div>
    </div>
    <div class="card-body">
        <% @orden.detalles_ordenes.includes(:producto).each do |item| %>
            <div class="row">
                <div class="col-xs-2 col-md-2">
                    <img class="img-responsive" src="http://placehold.it/120x80" alt="prewiew">
                </div>
                <div class="col-xs-4 col-md-6">
                    <h4 class="product-name"><strong>
                            <%= item.producto.nombre %>
                        </strong></h4>
                    <h4><small>
                            <%= item.producto.descripcion %>
                        </small></h4>
                </div>
                <div class="col-xs-6 col-md-4 row">
                    <div class="col-xs-6 col-md-6 text-right" style="padding-top: 5px">
                        <h6><strong>
                                <%= item.precio %> <span class="text-muted">x</span>
                            </strong></h6>
                    </div>
                    <div class="col-xs-4 col-md-4">
                        <%= item.cantidad %>
                    </div>
                    <div class="col-xs-2 col-md-2">
                    </div>
                </div>
            </div>
            <hr>
            <% end %>
    </div>
    <div class="card-footer">
        <%= form_with scope: :carro, url: pagar_con_paypal_carro_path(current_usuario.id) do |f| %>
            <%= f.hidden_field :orden_id, value: @orden.id %>
            <%= f.submit 'Pagar', class: 'btn btn-primary btn-sm' %>
        <% end %>

        <div class="pull-right" style="margin: 5px">
            Total: $<b>
            <%= @orden.total %>
            </b>
        </div>
    </div>
</div>