config/routes.rb
Rails.application.routes.draw do
  root 'home#index' 
  devise_for :usuarios
  devise_for :administradores
  resources :productos
  resources :categorias
  resources :carros, only: [:show, :update] do
    member do 
      post  :pagar_con_paypal
      get   :procesar_pago_paypal
    end
  end

end

app/views/partial/_footer.html.erb
<footer class="text-center text-white py-5" id="Footer">
  <!-- iconos de redes sociales con css  -->
  <div class="text-center">
    <div class="container ">

      <ul class="social_icons ">
        <li><a href="#"><i class="fab fa-facebook fa-3x" aria-hidden="true"></i></a></li>
        <li><a href="#"><i class="fab fa-instagram fa-3x" aria-hidden="true"></i></a></li>
        <li><a href="#"><i class="fab fa-linkedin fa-3x" aria-hidden="true"></i></a></li>
        <li><a href="#"><i class="fab fa-github fa-3x" aria-hidden="true"></i></a></li>
        <li><a href="#"><i class="fab fa-twitter fa-3x" aria-hidden="true"></i></a></li>

      </ul>
    </div>
  </div>

</footer>

app/views/partial/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container px-4 px-sm-0">
    <% if usuario_signed_in? %>
      <a class="navbar-brand" href="">
        <%= current_usuario.email %>
      </a>
      <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarSupportedContent" aria-expanded="false">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
          
          

          <li class="nav-item">
            <a class="nav-link text-white" href="#Sobre-Mi">
              <%= link_to "Productos" , root_path, class: "nav-link text-white " %>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-white" href="#Experiencia">
              <%= link_to "Categorias" , categorias_path, class: "nav-link text-white " %>
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link text-white" href="#Trabajos">
              <%= link_to "Cerrar Sesión" , destroy_usuario_session_path, data: {"turbo-method": :delete},
                class: "nav-link text-white " %>
            </a>
          </li>
          <li class="nav-item">
          <li class="nav-item">
            <a class="nav-link text-white" href="#Sobre-Mi">
              <%= link_to "Ver Carrito 🛒  " , "carros/show", class: "nav-link text-white " %>
            </a>
          </li>

            <% else %>
          <li class="nav-item">
            <a class="nav-link text-white" href="#Contacto">
              <%= link_to "inicia sesion" , new_usuario_session_path, class: "nav-link text-white " %>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-white" href="#Sobre-Mi">
              <%= link_to "Ver Carrito 🛒  " , "carros/show", class: "nav-link text-white " %>
            </a>
          </li>
          <%end%>

        </ul>
      </div>
  </div>
</nav>