config/routes.rb
Rails.application.routes.draw do
  root 'home#index' 
  devise_for :usuarios
  devise_for :administradores
  resources :productos
  resources :categorias
  resources :carros, only: [:show, :update] do
    member do 
      post  :pagar_con_paypal
      get   :procesar_pago_paypal
    end
  end

end

app/models/categoria.rb
class Categoria < ApplicationRecord
  has_and_belongs_to_many :productos

end

app/controllers/categorias_controller.rb
class CategoriasController < ApplicationController
  before_action :authenticate_administrador!

  before_action :set_categoria, only: %i[ show edit update destroy ]

  # GET /categorias or /categorias.json
  def index
    @categorias = Categoria.all
  end

  # GET /categorias/1 or /categorias/1.json
  def show
  end

  # GET /categorias/new
  def new
    @categoria = Categoria.new
  end

  # GET /categorias/1/edit
  def edit
  end

  # POST /categorias or /categorias.json
  def create
    @categoria = Categoria.new(categoria_params)

    respond_to do |format|
      if @categoria.save
        format.html { redirect_to categoria_url(@categoria), notice: "Categoria was successfully created." }
        format.json { render :show, status: :created, location: @categoria }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @categoria.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categorias/1 or /categorias/1.json
  def update
    respond_to do |format|
      if @categoria.update(categoria_params)
        format.html { redirect_to categoria_url(@categoria), notice: "Categoria was successfully updated." }
        format.json { render :show, status: :ok, location: @categoria }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @categoria.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categorias/1 or /categorias/1.json
  def destroy
    @categoria.destroy

    respond_to do |format|
      format.html { redirect_to categorias_url, notice: "Categoria was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_categoria
      @categoria = Categoria.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def categoria_params
      params.require(:categoria).permit(:nombre)
    end
end

app/helpers/categorias_helper.rb
module CategoriasHelper
end

app/views/categorias/_categoria.html.erb
<div id="<%= dom_id categoria %>">
  <p>
    <strong>Nombre:</strong>
    <%= categoria.nombre %>
  </p>

</div>

app/views/categorias/_form.html.erb
<%= form_with(model: categoria) do |form| %>
  <% if categoria.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(categoria.errors.count, "error") %> prohibited this categoria from being saved:</h2>

      <ul>
        <% categoria.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nombre, style: "display: block" %>
    <%= form.text_field :nombre %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/categorias/edit.html.erb
<h1>Editing categoria</h1>

<%= render "form", categoria: @categoria %>

<br>

<div>
  <%= link_to "Show this categoria", @categoria %> |
  <%= link_to "Back to categorias", categorias_path %>
</div>

app/views/categorias/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Categorias</h1>

<div id="categorias">
  <% @categorias.each do |categoria| %>
    <%= render categoria %>
    <p>
      <%= link_to "Show this categoria", categoria %>
    </p>
  <% end %>
</div>

<%= link_to "New categoria", new_categoria_path %>

app/views/categorias/new.html.erb
<h1>New categoria</h1>

<%= render "form", categoria: @categoria %>

<br>

<div>
  <%= link_to "Back to categorias", categorias_path %>
</div>

app/views/categorias/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @categoria %>

<div>
  <%= link_to "Edit this categoria", edit_categoria_path(@categoria) %> |
  <%= link_to "Back to categorias", categorias_path %>

  <%= button_to "Destroy this categoria", @categoria, method: :delete %>
</div>