config/routes.rb
Rails.application.routes.draw do
  root 'home#index' 
  devise_for :usuarios
  devise_for :administradores
  resources :productos
  resources :categorias
  resources :carros, only: [:show, :update] do
    member do 
      post  :pagar_con_paypal
      get   :procesar_pago_paypal
    end
  end

end

app/models/producto.rb
class Producto < ApplicationRecord
  has_and_belongs_to_many :categorias

  has_many :detalles_ordenes
  has_many :ordenes, through: :detalles_ordenes
end

app/controllers/productos_controller.rb
class ProductosController < ApplicationController
  before_action :authenticate_administrador!
  before_action :set_producto, only: %i[ show edit update destroy ]  # GET /productos or /productos.json
  def index
    @productos = Producto.all
  end

  # GET /productos/1 or /productos/1.json
  def show
  end

  # GET /productos/new
  def new
    @producto = Producto.new
  end

  # GET /productos/1/edit
  def edit
  end

  # POST /productos or /productos.json
  def create
    @producto = Producto.new(producto_params)

    respond_to do |format|
      if @producto.save
        format.html { redirect_to producto_url(@producto), notice: "Producto was successfully created." }
        format.json { render :show, status: :created, location: @producto }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /productos/1 or /productos/1.json
  def update
    respond_to do |format|
      if @producto.update(producto_params)
        format.html { redirect_to producto_url(@producto), notice: "Producto was successfully updated." }
        format.json { render :show, status: :ok, location: @producto }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /productos/1 or /productos/1.json
  def destroy
    @producto.destroy

    respond_to do |format|
      format.html { redirect_to productos_url, notice: "Producto was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_producto
      @producto = Producto.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def producto_params
      params.require(:producto).permit(:nombre, :descripcion, :stock, :precio, :sku, categoria_ids: [])
    end
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/views/productos/_form.html.erb
<%= form_with(model: producto) do |form| %>
  <% if producto.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(producto.errors.count, "error") %> prohibited this producto from being saved:</h2>

      <ul>
        <% producto.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nombre, style: "display: block" %>
    <%= form.text_field :nombre %>
  </div>

  <div>
    <%= form.label :descripcion, style: "display: block" %>
    <%= form.text_area :descripcion %>
  </div>

  <div>
    <%= form.label :stock, style: "display: block" %>
    <%= form.number_field :stock %>
  </div>

  <div>
    <%= form.label :precio, style: "display: block" %>
    <%= form.text_field :precio %>
  </div>

  <div>
    <%= form.label :sku, style: "display: block" %>
    <%= form.text_field :sku %>
  </div>

  <div class="field">
    <%= form.label :categorias %>
    <%= form.collection_check_boxes :categoria_ids, Categoria.all, :id, :nombre do |b| %>
    <%= b.check_box + b.text %>
    <% end %>
  </div>


  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/productos/_producto.html.erb
<div id="<%= dom_id producto %>">
  <p>
    <strong>Nombre:</strong>
    <%= producto.nombre %>
  </p>

  <p>
    <strong>Descripcion:</strong>
    <%= producto.descripcion %>
  </p>

  <p>
    <strong>Stock:</strong>
    <%= producto.stock %>
  </p>

  <p>
    <strong>Precio:</strong>
    <%= producto.precio %>
  </p>

  <p>
    <strong>Sku:</strong>
    <%= producto.sku %>
  </p>

</div>

app/views/productos/edit.html.erb
<h1>Editing producto</h1>

<%= render "form", producto: @producto %>

<br>

<div>
  <%= link_to "Show this producto", @producto %> |
  <%= link_to "Back to productos", productos_path %>
</div>

app/views/productos/index.html.erb
<p style="color: green"><%= notice %></p>
<%= link_to "New producto", new_producto_path %>

<h1>Productos</h1>

<!-- app/views/home/index.html.erb -->
<div class="row">
    <div class="col-md-8 offset-2">
        <div class="container">
            <div class="row">
                <% @productos.each do |producto| %>
                    <div class="col-md-3">
                        <div class="card">
                            <img class="card-img-top" src="https://dummyimage.com/600x400/c7c7c7/737373&text=image" alt="<%=producto.nombre%>" />
                            <div class="card-block">
                                <h5 class="card-title">
                                    <%= producto.nombre %>
                                </h5>
                                <div class="card-text">
                                    <div class="badge badge-primary">
                                        <%= producto.categorias.first.nombre %>
                                    </div>
                                    <div>$<%= producto.precio %>
                                    </div>
                                </div>
                                <div class="row float-right">
                                    <div class="col-md-12">
                                        <button class="btn btn-primary btn-sm">
                                            Add to cart</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/productos/new.html.erb
<h1>New producto</h1>

<%= render "form", producto: @producto %>

<br>

<div>
  <%= link_to "Back to productos", productos_path %>
</div>

app/views/productos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @producto %>

<div>
  <%= link_to "Edit this producto", edit_producto_path(@producto) %> |
  <%= link_to "Back to productos", productos_path %>

  <%= button_to "Destroy this producto", @producto, method: :delete %>
</div>